version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    # IMPORTANT: env file lives ONLY on the server
    env_file: /srv/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
