version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    env_file: /srv/app/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 10
    # IMPORTANT: no ports here; nginx will be the only one exposing 80

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - /srv/app/site:/usr/share/nginx/html:ro
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
