services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: lorangerose_admin
      POSTGRES_PASSWORD: apppass
      POSTGRES_DB: lorangerose
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lorangerose_admin -d lorangerose"]
      interval: 3s
      timeout: 3s
      retries: 15

  backend:
    build: { context: ./backend }
    container_name: yourapp-backend
    ports: ["3000:3000"]
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://lorangerose_admin:apppass@db:5432/lorangerose
      SHADOW_DATABASE_URL: postgresql://lorangerose_admin:apppass@db:5432/lorangerose_shadow
      JWT_SECRET: dev-please-change
      CORS_ORIGIN: http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
      - ./backend/uploads:/app/uploads
    command: sh -lc "npx prisma db push && npm run dev"

  frontend:
    build: { context: ./frontend }
    container_name: yourapp-frontend
    ports: ["5173:5173"]
    environment:
      - DOCKER=1
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - TAILWIND_MODE=watch
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: sh -lc "npm run dev -- --host 0.0.0.0 --port 5173"

volumes:
  pgdata:
