services:
  api:
    image: ghcr.io/0isoft/lorangerose-api:latest   # or keep build: if you still build on server
    env_file:
      - ./backend/.env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/health').then(r=>process.exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 10

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
      - "80:80"
    volumes:
      - /srv/app/site:/usr/share/nginx/html:ro
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
