services:
  api:
    image: ghcr.io/0isoft/lorangerose-api:latest   # or keep build: if you still build on>
    env_file:
    - ./backend/.env
    command:
    - sh
    - -lc
    - |
        PRISMA="npx --yes prisma@6.16.1"
        echo "Prisma generate.."
        $$PRISMA generate
        echo "Migrate deploy.."
        $$PRISMA migrate deploy
        echo "Starting API"
        node dist/index.js
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000/health').then(r=>process.>exit(r.ok?0:1)).catch(()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 10
    volumes:
      - uploads:/app/uploads # API writes here to match the code

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - api
    ports:
    - "80:80"
    - "443:443" 
    volumes:
      - /srv/app/site:/usr/share/nginx/html
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
      - uploads:/var/www/uploads:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro 
    restart: unless-stopped

volumes:
  uploads: