name: Deploy Backend (pull image on server)

on:
  workflow_run:
    workflows: ["Build & Push API Image"]
    types: [completed]
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: deploy-backend
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Prepare SSH key (from base64)
        shell: bash
        run: |
          echo "$LS_SSH_KEY_B64" | base64 -d > key.pem
          chmod 644 key.pem
          ls -l key.pem
        env:
          LS_SSH_KEY_B64: ${{ secrets.LS_SSH_KEY_B64 }}

      - name: SSH & pull latest image, restart
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LS_HOST }}
          username: ubuntu
          key_path: key.pem
          script: |
            set -e
            cd /srv/app/your-repo
            echo "$TOKEN" | docker login ghcr.io -u "$USER" --password-stdin
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
        env:
          USER:  ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
