name: Deploy Backend (pull image on server)

on:
  workflow_run:
    workflows: ["Build & Push API Image"]
    types: [completed]
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
      - "ops/**"
      - "docker-compose.prod.yml"
      - ".github/workflows/backend-deploy.yml"
  workflow_dispatch: {}

concurrency:
  group: deploy-backend
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name != 'workflow_run' }}
    runs-on: ubuntu-latest

    steps:
      - name: Prepare SSH key (from base64)
        shell: bash
        run: |
          echo "$LS_SSH_KEY_B64" | base64 -d > key.pem
          chmod 644 key.pem
        env:
          LS_SSH_KEY_B64: ${{ secrets.LS_SSH_KEY_B64 }}

      - name: Update repo & restart services
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LS_HOST }}
          username: ubuntu
          key_path: key.pem
          envs: GHCR_USER,GHCR_PAT
          script: |
            set -e

            # choose repo dir (yours is /srv/app)
            if [ -d /srv/app/your-repo ]; then
              cd /srv/app/your-repo
            else
              cd /srv/app
            fi

            # fetch latest code (nginx.conf, compose, etc.)
            git fetch --all
            git reset --hard origin/main

            # require backend .env
            if [ ! -f ./backend/.env ]; then
              echo "ERROR: ./backend/.env missing on server (expected next to compose)."; exit 1
            fi

            # login to GHCR only if creds are present; skip if image is public
            if [ -n "$GHCR_PAT" ] && [ -n "$GHCR_USER" ]; then
              echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USER" --password-stdin
            fi

            # pull updated images and restart
            docker compose -f docker-compose.prod.yml pull || true
            docker compose -f docker-compose.prod.yml up -d

            # pick up updated nginx.conf (MIME types fix)
            docker compose -f docker-compose.prod.yml restart nginx
        env:
          GHCR_USER: ${{ secrets.GHCR_USER }}
          GHCR_PAT:  ${{ secrets.GHCR_PAT }}
