# .github/workflows/backend-deploy.yml
name: Deploy Backend (pull image on server)

on:
  workflow_run:
    workflows: ["Build & Push API Image"]
    types: [completed]
    branches: [ main ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: SSH & pull latest image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LS_HOST }}
          username: ubuntu
          key: ${{ secrets.LS_SSH_KEY }}
          script: |
            set -e
            cd /srv/app/your-repo
            docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
