- name: Prepare SSH key
  shell: bash
  run: |
    echo "$LS_SSH_KEY_B64" | base64 -d > key.pem
    chmod 600 key.pem
  env:
    LS_SSH_KEY_B64: ${{ secrets.LS_SSH_KEY_B64 }}

- name: SSH & pull + restart
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.LS_HOST }}
    username: ubuntu
    key_path: key.pem
    script: |
      set -e
      cd /srv/app/your-repo
      docker login ghcr.io -u $GITHUB_ACTOR -p ${{ secrets.GITHUB_TOKEN }}
      docker compose -f docker-compose.prod.yml pull
      docker compose -f docker-compose.prod.yml up -d
