name: Build & Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        working-directory: frontend
        env:
          VITE_API_BASE: /api
        run: |
          npm ci --no-audit --no-fund
          npm run build
          ls -lah dist
          test -f dist/index.html || (echo "no dist/index.html" && exit 1)

      - name: Prepare SSH key (from base64)
        shell: bash
        run: |
          echo "$LS_SSH_KEY_B64" | base64 -d > key.pem
          chmod 644 key.pem
        env:
          LS_SSH_KEY_B64: ${{ secrets.LS_SSH_KEY_B64 }}

      - name: Clean remote site dir
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LS_HOST }}
          username: ubuntu
          key_path: key.pem
          script: |
            mkdir -p /srv/app/site
            rm -rf /srv/app/site/*

      - name: Upload dist to Lightsail (flatten to /srv/app/site)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LS_HOST }}
          username: ubuntu
          key_path: key.pem
          source: "frontend/dist/**"
          target: "/srv/app/site"
          strip_components: 2     # <-- unwrap "frontend/dist"
          overwrite: true
          timeout: 120s
          command_timeout: 5m

      - name: Verify files on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LS_HOST }}
          username: ubuntu
          key_path: key.pem
          script: |
            ls -lah /srv/app/site | sed -n '1,100p'
            test -f /srv/app/site/index.html || (echo "index.html missing" && exit 1)
