name: Build & Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        working-directory: frontend
        run: |
          npm ci --no-audit --no-fund
          npm run build

      - name: Prepare SSH key (from base64)
        shell: bash
        run: |
          echo "$LS_SSH_KEY_B64" | base64 -d > key.pem
          # allow container user to read it (Go SSH client doesn’t care about 600)
          chmod 644 key.pem
          ls -l key.pem
        env:
          LS_SSH_KEY_B64: ${{ secrets.LS_SSH_KEY_B64 }}

      - name: SSH connectivity check
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LS_HOST }}
          username: ubuntu
          key_path: key.pem
          script: |
            whoami
            ls -la /srv/app/site || true

      - name: Upload dist to Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LS_HOST }}
          username: ubuntu
          key_path: key.pem
          source: "frontend/dist/*"
          target: "/srv/app/site"
          port: 22
          timeout: 120s
          command_timeout: 5m
