# .github/workflows/frontend-deploy.yml
name: Build & Deploy Frontend

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - ".github/workflows/frontend-deploy.yml"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install & Build
        working-directory: frontend
        run: |
          npm ci --no-audit --no-fund
          npm run build

      - name: Upload to Lightsail
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.LS_HOST }}         # e.g. 13.38.177.81
          username: ubuntu
          key: ${{ secrets.LS_SSH_KEY }}      # your PEM content
          source: "frontend/dist/*"
          target: "/srv/app/site"
          strip_components: 2
