- name: Prepare SSH key
  shell: bash
  run: |
    echo "$LS_SSH_KEY_B64" | base64 -d > key.pem
    chmod 600 key.pem
  env:
    LS_SSH_KEY_B64: ${{ secrets.LS_SSH_KEY_B64 }}

- name: SSH connectivity check
  uses: appleboy/ssh-action@v1.0.3
  with:
    host: ${{ secrets.LS_HOST }}
    username: ubuntu
    key_path: key.pem
    script: |
      whoami
      ls -la /srv/app/site || true

- name: Upload dist to Lightsail
  uses: appleboy/scp-action@v0.1.7
  with:
    host: ${{ secrets.LS_HOST }}
    username: ubuntu
    key_path: key.pem
    source: "frontend/dist/*"
    target: "/srv/app/site"
    port: 22
    timeout: 120s
    command_timeout: 5m
